# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Tao Sun
description: "Homepage of Tao Sun"
keywords: "Data Science, Voyage"
url: https://taosunvoyage.github.io
baseurl: ""

# google_analytics:
repo: http://github.com/taosunvoyage/
# disqus_shortname:
# disqus_site_shortname:

# Author settings
author:
  name: Tao Sun
  greetings: "Hi there! Welcome to my personal page."
  thumb: /images/author.jpg
  email: taosun.data@gmail.com
  url: https://taosunvoyage.github.io/
  github: https://github.com/taosunvoyage
  # twitter:
  # facebook:
  linkedin: https://linkedin.com/in/taosunvoyage

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: projects
    title: Projects
  - slug: talks
    title: Talks
  - slug: posts
    title: Posts


exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
